name: modsecurity

services:
  waf:
    build: .
    user: "1001330001"
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      BACKEND: "http://backend:9000"
      PARANOIA: 4
      ANOMALY_INBOUND: 5
      ANOMALY_OUTBOUND: 4
      ACCESSLOG: "/proc/self/fd/1"

  backend:
    image: "docker.io/kennethreitz/httpbin"
    command: ["gunicorn", "-b", "0.0.0.0:9000", "httpbin:app", "-k", "gevent"]
