name: modsecurity

services:
  waf:
    build: .
    user: "1001330001"
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      BACKEND: "http://backend:9000"
      BLOCKING_PARANOIA: 4
      ANOMALY_INBOUND: 5
      ANOMALY_OUTBOUND: 4
      ACCESSLOG: "/proc/self/fd/1"
    volumes:
      - type: bind
        source: ./config/custom-rules/init-crs.dist
        target: /opt/modsecurity/rules/init-crs 
      - type: bind
        source: ./config/custom-rules/before-crs.dist
        target: /opt/modsecurity/rules/before-crs.dist
      - type: bind
        source: ./config/custom-rules/after-crs.dist
        target: /opt/modsecurity/rules/after-crs.dist
  backend:
    image: "docker.io/kennethreitz/httpbin"
    command: ["gunicorn", "-b", "0.0.0.0:9000", "httpbin:app", "-k", "gevent"]

