# /etc/modsecurity.d/setup.conf

Include conf/extra/httpd-logging-before-modsec.conf
Include /etc/modsecurity.d/modsecurity.conf
Include /etc/modsecurity.d/modsecurity-override.conf
Include conf/extra/httpd-logging-after-modsec.conf
Include conf/extra/httpd-logging-vshn.conf


IncludeOptional /opt/modsecurity/rules/init-crs/*.conf
Include /opt/modsecurity/rules/before-crs.dist/*.conf
IncludeOptional /opt/modsecurity/rules/before-crs/*.conf


Include /etc/modsecurity.d/owasp-crs/crs-setup.conf

Include /etc/modsecurity.d/owasp-crs/plugins/*-config.conf
Include /etc/modsecurity.d/owasp-crs/plugins/*-before.conf

Include /etc/modsecurity.d/owasp-crs/rules/*.conf

Include /etc/modsecurity.d/owasp-crs/plugins/*-after.conf

Include /opt/modsecurity/rules/after-crs.dist/*.conf
IncludeOptional /opt/modsecurity/rules/after-crs/*.conf
