name: modsecurity

services:
  waf:
    build: .
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      BACKEND: "http://backend:9000"

    # Simulate OpenShift by using a random UID and GID, as well as GID 0
    user: "1001140000:1001140000"
    group_add:
      - root

    # Simulate an emptyDir volume. Required for apache to write its PID file
    tmpfs:
      - "/usr/local/apache2/logs:mode=770"

    develop:
      watch:
        - action: rebuild
          path: .

  backend:
    image: "docker.io/kennethreitz/httpbin"
    command: ["gunicorn", "-b", "0.0.0.0:9000", "httpbin:app", "-k", "gevent"]
