name: modsecurity
services:
  waf:
    build: .
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      BACKEND: "http://backend:9000"
      BLOCKING_PARANOIA: 0
      ANOMALY_INBOUND: 1
      ANOMALY_OUTBOUND: 1
      MODSEC_DEBUG_LOGLEVEL: 0
      MODSEC_AUDIT_ENGINE: on
      MODSEC_AUDIT_LOG: /dev/stdout
      LOGLEVEL: warn
      ERRORLOG: /dev/stderr
      PARANOIA: 1
      EXECUTING_PARANOIA: 2
      ENFORCE_BODYPROC_URLENCODED: 1
      ALLOWED_METHODS: "GET POST PUT"
      ALLOWED_REQUEST_CONTENT_TYPE: "text/xml|application/xml|text/plain"
      ALLOWED_REQUEST_CONTENT_TYPE_CHARSET: "utf-8|iso-8859-1"
      ALLOWED_HTTP_VERSIONS: "HTTP/1.1 HTTP/2 HTTP/2.0"
      RESTRICTED_EXTENSIONS: ".cmd/ .com/ .config/ .dll/"
      RESTRICTED_HEADERS: "/proxy/ /if/"
      STATIC_EXTENSIONS: "/.jpg/ /.jpeg/ /.png/ /.gif/"
      MAX_NUM_ARGS: 128
      ARG_NAME_LENGTH: 50
      ARG_LENGTH: 200
      TOTAL_ARG_LENGTH: 6400
      MAX_FILE_SIZE: 100000
      COMBINED_FILE_SIZES: 1000000
      TIMEOUT: 60
      SERVER_ADMIN: root@localhost
      SERVER_NAME: localhost
      PORT: 8080
      MODSEC_RULE_ENGINE: on
      MODSEC_REQ_BODY_ACCESS: on
      MODSEC_REQ_BODY_LIMIT: 13107200
      MODSEC_REQ_BODY_NOFILES_LIMIT: 131072
      MODSEC_RESP_BODY_ACCESS: on
      MODSEC_RESP_BODY_LIMIT: 524288
      MODSEC_PCRE_MATCH_LIMIT: 1000
      MODSEC_PCRE_MATCH_LIMIT_RECURSION: 1000
      VALIDATE_UTF8_ENCODING: 1
      CRS_ENABLE_TEST_MARKER: 1

  backend:
    image: "docker.io/kennethreitz/httpbin"
    command: ["gunicorn", "-b", "0.0.0.0:9000", "httpbin:app", "-k", "gevent"]
