version: '3'
services:
  waf:
    build: .
    environment:
      BACKEND: http://backend
    ports:
    - "8080:8080"
    links:
    - backend
  backend:
    image: docker.io/kennethreitz/httpbin
    ports: 
    - "80"
