# Custom rules before initializing CRS (ids: 9900-99999)
#
# JSON bodies with large amounts of ARGS let the Apache child process crash.
# We disable the requestBodyProcessor=JSON for specific requests (path and client IPs) so that the ARGS are not filled and tested.
# https://github.com/SpiderLabs/ModSecurity/blob/v3/master/modsecurity.conf-recommended#L29
#
SecRule REQUEST_URI "@beginsWith /third-eyes/third-eyes/callback" \
  "phase:1,nolog,pass,id:9901,\
  chain"
  SecRule REMOTE_ADDR "@ipMatch 20.23.211.36,20.82.20.235,20.101.204.16,20.101.203.9" \
    "ctl:ruleRemoveById=200001"

