name: Test
on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Build image
        run: docker build -t test -f Containerfile .
      - name: Run image
        run: docker run -d --name apache test
      - name: Verify
        run: |
          [ $(docker inspect apache --format='{{.State.Running}}') = 'true' ]
